# Generated by Django 5.1.7 on 2025-03-30 03:07

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=core.models.get_data_file_path)),
                ('data_type', models.CharField(choices=[('spectrometer', 'Optical Spectrometer Data'), ('image', 'Digital Camera Image')], max_length=20)),
                ('cancer_type', models.CharField(choices=[('breast', 'Breast Cancer'), ('throat', 'Throat Cancer'), ('skin', 'Skin Cancer'), ('other', 'Other Cancer Type'), ('screening', 'General Screening')], max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_category', models.CharField(default='healthcare', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('cancer_probability', models.FloatField(blank=True, null=True)),
                ('biomarkers', models.JSONField(blank=True, null=True)),
                ('spectral_signatures', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('result_summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('healthcare_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='core.healthcaredata')),
            ],
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to=core.models.get_data_file_path)),
                ('data_type', models.CharField(choices=[('spectrometer', 'Optical Spectrometer Data'), ('multi_param', 'Multi-parameter Soil Sensor Data'), ('moisture', 'Capacitive Soil Moisture Data')], max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('farm_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_category', models.CharField(default='farming', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoilAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('moisture_content', models.FloatField(blank=True, null=True)),
                ('nutrient_levels', models.JSONField(blank=True, null=True)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('soil_health_score', models.FloatField(blank=True, null=True)),
                ('result_summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('soil_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='core.soildata')),
            ],
        ),
    ]
